
[ClassVersion("1.0.0.0"), FriendlyName("AuditPolicySubcategoryGuid")]
class MSFT_AuditPolicySubcategoryGuid : OMI_BaseResource
{
    [Key, Description("The GUID of the Subcategory to be configured.")] String Id;
    [Key, Description("The audit flag to be configured."), ValueMap{"Success","Failure"}, Values{"Success","Failure"}] String AuditFlag;
    [Write, Description("Specifies whether the flag should be enabled or disabled. To enable the flag, set this property to Present. To disable the flag, set this property to Absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

